[project]
name = "langgraph-agent-course"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=6.29.5",
    "langchain>=0.3.26",
    "langgraph>=0.4.8",
    "langsmith>=0.4.1",
]
